### ISSUE TITLE
Agent fails to parse CPU usage on systems using European locale

### ISSUE THREAD

**Issue by sophokles73** [eclipse-iofog/Agent#329]
The awk command used for determining the agent's CPU utilization assumes the output to use a `.` as the decimal limiter. However, on a system using European (here: German) locale, the value output uses a `,` as decimal limiter which leads to a failure to parse the value using Java's `Float.parseFloat()` method.
I can see two options to fix this:
1. Prepend the awk command with a `LC_NUMERIC=en_US.UTF-8` && ` in order to use a decimal point instead of a comma when formatting floats, or
1. Prevent the problem by not outputting a float in the first place. I doubt the value of knowing that the CPU utilization is `56.345` instead of `56` percent. Thus, the awk command could be changed to format the output like this:
    ```bash
    grep 'cpu' /proc/stat | awk '{usage=($2+$3+$4)*100/($2+$3+$4+$5+$6+$7+$8+$9)} END {printf (%d, usage)}'
    ```
   And then parse the value using `Integer.parseInt()` ...

**Comment by NehaNaithani** [comment]
Hi @sophokles73, 
The fix is added and will be released with 3.0.0 release.
Closing the issue.
Thanks.
