### ISSUE TITLE
Declare dependency on Java

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/Agent#358]
The agent requires Java to run. Installing the `deb` package does not install a JRE. So that running the Agent will fail:

~~~
pi@raspberrypi:~/deploy $ sudo /etc/init.d/iofog-agent start
Starting iofog-agent service...
Using Java version  found at ''
/etc/init.d/iofog-agent: 30: /etc/init.d/iofog-agent: java: not found
~~~

**Comment by NehaNaithani** [comment]
Hi @ctron,
The fix is added and will be released with 3.0.0 release.
Closing the issue.
Thanks.
